{"name":"Create Web Image Url Tables","ppdf:dataflowId":"274ba827-63bb-4400-b0f8-0a789bfdd8c3","ppdf:owner":{"tenantId":"a19b42cb-2caf-4dbb-8af9-fcbe17bd6b14","userId":"2576c048-a948-468c-a5fd-7f2eb769f9c8"},"ppdf:fastCopy":true,"version":"1.0","culture":"en-US","modifiedTime":"2025-02-25T21:39:09.0996784+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":true,"queriesMetadata":{"DimEmployeeImage":{"queryId":"18063822-7ca6-4c19-b97f-ee43db40c8e1","queryName":"DimEmployeeImage","loadEnabled":true},"DimProductImage":{"queryId":"9053fd01-dc93-4458-9760-72248c6abd14","queryName":"DimProductImage","loadEnabled":true},"DimSalesTerritoryImage":{"queryId":"d9b86273-3cc7-4416-8332-d72d39a31098","queryName":"DimSalesTerritoryImage","loadEnabled":true}},"document":"section Section1;\r\nshared DimEmployeeImage = let\n  Source = Sql.Database(\"znbjxinpfs5u3cxz7s7bppllcq-ilhmootuvz6u5cwdltudlcrq34.datawarehouse.fabric.microsoft.com\", \"AdventureWorks_Database\"),\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"DimEmployee\"]}[Data],\n  #\"Removed columns\" = Table.RemoveColumns(#\"Navigation 1\", {\"Status\", \"EndDate\", \"StartDate\", \"DepartmentName\", \"SalesPersonFlag\", \"CurrentFlag\", \"SickLeaveHours\", \"VacationHours\", \"BaseRate\", \"PayFrequency\", \"Gender\", \"SalariedFlag\", \"EmergencyContactPhone\", \"EmergencyContactName\", \"MaritalStatus\", \"Phone\", \"EmailAddress\", \"LoginID\", \"BirthDate\", \"HireDate\", \"Title\", \"NameStyle\", \"MiddleName\", \"LastName\", \"FirstName\", \"SalesTerritoryKey\", \"ParentEmployeeNationalIDAlternateKey\", \"EmployeeNationalIDAlternateKey\", \"ParentEmployeeKey\"}),\n  #\"Added Custom1\" = Table.AddColumn(#\"Removed columns\", \"Custom1\", each Text.Replace([EmployeePhotoUrl], \"/Files/resources/\", \"/Files/resources/DimEmployee/\")),\n  #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"Custom2\", each Text.Replace([Custom1], \"https://onelake.dfs.fabric.microsoft.com/3ac7ce42-ae74-4e7d-8ac3-5ce8358a30df/50402dac-ce50-4831-af2b-7d65ca8fe7db/Files/resources/\", \"https://fabricfutureinnovators-my.sharepoint.com/personal/gary_csaniz_ffi-services_com/Documents/Resources/\")),\n  #\"Added Custom\" = Table.AddColumn(#\"Added Custom2\", \"EmployeePhotoWebUrl\", each [Custom2]),\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\", {\"Custom1\", \"Custom2\", \"EmployeePhotoUrl\"})\nin\n  #\"Removed Columns\";\r\nshared DimProductImage = let\n  Source = Sql.Database(\"znbjxinpfs5u3cxz7s7bppllcq-ilhmootuvz6u5cwdltudlcrq34.datawarehouse.fabric.microsoft.com\", \"AdventureWorks_Database\"),\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"DimProduct\"]}[Data],\n  #\"Removed columns\" = Table.RemoveColumns(#\"Navigation 1\", {\"ProductAlternateKey\", \"ProductSubcategoryKey\", \"WeightUnitMeasureCode\", \"SizeUnitMeasureCode\", \"EnglishProductName\", \"SpanishProductName\", \"FrenchProductName\", \"StandardCost\", \"FinishedGoodsFlag\", \"Color\", \"SafetyStockLevel\", \"ReorderPoint\", \"ListPrice\", \"Size\", \"SizeRange\", \"Weight\", \"DaysToManufacture\", \"ProductLine\", \"DealerPrice\", \"Class\", \"Style\", \"ModelName\", \"EnglishDescription\", \"FrenchDescription\", \"ChineseDescription\", \"ArabicDescription\", \"HebrewDescription\", \"ThaiDescription\", \"GermanDescription\", \"JapaneseDescription\", \"TurkishDescription\", \"StartDate\", \"EndDate\", \"Status\"}),\n  #\"Added Custom1\" = Table.AddColumn(#\"Removed columns\", \"Custom1\", each Text.Replace([LargePhotoUrl], \"/Files/resources/\", \"/Files/resources/DimProduct/\")),\n  #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"Custom2\", each Text.Replace([Custom1], \"https://onelake.dfs.fabric.microsoft.com/3ac7ce42-ae74-4e7d-8ac3-5ce8358a30df/50402dac-ce50-4831-af2b-7d65ca8fe7db/Files/resources/\", \"https://fabricfutureinnovators-my.sharepoint.com/personal/gary_csaniz_ffi-services_com/Documents/Resources/\")),\n  #\"Added Custom\" = Table.AddColumn(#\"Added Custom2\", \"LargePhotoWebUrl\", each [Custom2]),\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\", {\"Custom1\", \"Custom2\", \"LargePhotoUrl\"})\nin\n  #\"Removed Columns\";\r\nshared DimSalesTerritoryImage = let\n  Source = Sql.Database(\"znbjxinpfs5u3cxz7s7bppllcq-ilhmootuvz6u5cwdltudlcrq34.datawarehouse.fabric.microsoft.com\", \"AdventureWorks_Database\"),\n  #\"Navigation 1\" = Source{[Schema = \"dbo\", Item = \"DimSalesTerritory\"]}[Data],\n  #\"Removed columns\" = Table.RemoveColumns(#\"Navigation 1\", {\"SalesTerritoryAlternateKey\", \"SalesTerritoryRegion\", \"SalesTerritoryCountry\", \"SalesTerritoryGroup\"}),\n  #\"Added Custom1\" = Table.AddColumn(#\"Removed columns\", \"Custom1\", each Text.Replace([SalesTerritoryImageUrl], \"/Files/resources/\", \"/Files/resources/DimSalesTerritory/\")),\n  #\"Added Custom2\" = Table.AddColumn(#\"Added Custom1\", \"Custom2\", each Text.Replace([Custom1], \"https://onelake.dfs.fabric.microsoft.com/3ac7ce42-ae74-4e7d-8ac3-5ce8358a30df/50402dac-ce50-4831-af2b-7d65ca8fe7db/Files/resources/\", \"https://fabricfutureinnovators-my.sharepoint.com/personal/gary_csaniz_ffi-services_com/Documents/Resources/\")),\n  #\"Added Custom\" = Table.AddColumn(#\"Added Custom2\", \"SalesTerritoryImageWebUrl\", each [Custom2]),\n  #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\", {\"Custom1\", \"Custom2\", \"SalesTerritoryImageUrl\"})\nin\n  #\"Removed Columns\";\r\n","connectionOverrides":[{"path":"znbjxinpfs5u3cxz7s7bppllcq-ilhmootuvz6u5cwdltudlcrq34.datawarehouse.fabric.microsoft.com;AdventureWorks_Database","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"SQL\",\"path\":\"znbjxinpfs5u3cxz7s7bppllcq-ilhmootuvz6u5cwdltudlcrq34.datawarehouse.fabric.microsoft.com;AdventureWorks_Database\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"DimEmployeeImage","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DimEmployeeImage.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"EmployeeKey","dataType":"int64"},{"name":"EmployeePhotoWebUrl","dataType":"string"}]},{"$type":"LocalEntity","name":"DimProductImage","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DimProductImage.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"ProductKey","dataType":"int64"},{"name":"LargePhotoWebUrl","dataType":"string"}]},{"$type":"LocalEntity","name":"DimSalesTerritoryImage","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DimSalesTerritoryImage.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"SalesTerritoryKey","dataType":"int64"},{"name":"SalesTerritoryImageWebUrl","dataType":"string"}]}]}